language : python
cache : false

matrix :
    allow_failures:
        python: 3.8
    include :
        - os : linux
          python : 3.6
        - os : linux
          python : 3.7
        - os : linux
          python : 3.8
        - os : osx
          python : 3.6
        - os : osx
          python : 3.7
        - os : osx
          python : 3.8

addons:
  apt:
    packages:
        - wget
  homebrew:
    packages:
        - wget

before_install :
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda

install :
    - conda install --yes python=$TRAVIS_PYTHON_VERSION scipy
    - pip install codecov
    - python setup.py install
    - python scripts/nltk_helper.py

script : py.test --cov=niacin

after_success :
    - codecov

notifications :
    email :
        recipients :
            - dillon.niederhut@gmail.com
        on_success : change
        on_failure : change
