language : generic
cache : false

matrix :
    include :
        - os : linux
          env :
              - PY_MAJOR_MINOR="3.6"
              - INSTALL_FILE="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
        - os : linux
          env :
              - PY_MAJOR_MINOR="3.7"
              - INSTALL_FILE="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"
        - os : linux
          env :
              - PY_MAJOR_MINOR="3.8"
              - INSTALL_FILE="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh"

addons:
  apt:
    packages:
        - wget
  homebrew:
    packages:
        - wget

before_install :
    - wget $INSTALL_FILE -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda create -q -n test-environment python=$PY_MAJOR_MINOR scipy
    - source activate test-environment
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export CC=clang;export CXX=clang++;export CFLAGS='-stdlib=libc++'; fi

install :
    - pip install -qqq pytest pytest-cov codecov
    - pip install -qqq .[all]
    - travis_wait python scripts/fairseq_helper.py

script : py.test --cov=niacin

after_success :
    - codecov

notifications :
    email :
        recipients :
            - dillon.niederhut@gmail.com
        on_success : change
        on_failure : change
