language : python
cache : false

matrix :
    allow_failures:
        python: 3.8
    include :
        - os : linux
          python : 3.6
        - os : linux
          python : 3.7
        - os : linux
          python : 3.8
        - os : osx
          python : 3.6
        - os : osx
          python : 3.7
        - os : osx
          python : 3.8

addons:
  apt:
    packages:
        - wget
  homebrew:
    packages:
        - wget

before_install :
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION scipy
    - source activate test-environment

install :
    - pip install pytest pytest-cov codecov
    - python setup.py install
    - python scripts/nltk_helper.py

script : py.test --cov=niacin

after_success :
    - codecov

notifications :
    email :
        recipients :
            - dillon.niederhut@gmail.com
        on_success : change
        on_failure : change
